name: Rust
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project-directory: ['desktop', 'chip8_core']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Rust environment
        uses: actions-rs/toolchain@v2
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Cache cargo registry
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ matrix.project-directory }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Build project
        run: cargo build --release
        working-directory: ${{ matrix.project-directory }}

      - name: Run tests
        run: cargo test
        working-directory: ${{ matrix.project-directory }}

